[project]
name = "comfyui-nsfw-detection"
description = "Nodes: NudenetDetector"
version = "1.0.0"
license = "LICENSE"
dependencies = ["coloredlogs==15.0.1", "flatbuffers==24.3.25", "humanfriendly==10.0", "mpmath==1.3.0", "numpy==1.26.4", "onnx==1.16.0", "onnxruntime==1.17.3", "opencv-python-headless==4.9.0.80", "packaging==24.0", "protobuf==5.26.1", "sympy==1.12"]

[project.urls]
Repository = "https://github.com/katalist-ai/comfyUI-nsfw-detection"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "comfyUI-nsfw-detection"
Icon = ""
